name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: build-output
          path: .
          if-no-files-found: error
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-output
          path: .

      - name: Deploy the app to `gh-pages`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: false # Keep commit logs so that you can track CSV revisions
